const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const id = String(process.argv[2] || "").trim();

if (!/^[a-z0-9][a-z0-9_-]*$/.test(id)) {
  console.error("usage: node scripts/create-plugin.js <id>");
  console.error("id must match /^[a-z0-9][a-z0-9_-]*$/");
  process.exit(1);
}

const dir = path.join(root, "plugins", id);
if (fs.existsSync(dir)) {
  console.error(`plugin already exists: ${path.relative(root, dir)}`);
  process.exit(1);
}

fs.mkdirSync(path.join(dir, "tests"), { recursive: true });

write("plugin.json", {
  id,
  title: titleFromID(id),
  version: "0.1.0",
  api_version: "1",
  min_host_version: readHostVersion(),
  description: `${titleFromID(id)} plugin.`,
  homepage: "docs/plugin-platform.md",
  repository: "local",
  keywords: [id],
  license: "UNLICENSED",
  priority: 100,
  default_enabled: false,
  scope: "both",
  permissions: {
    required: [],
    optional: [],
  },
  hooks: ["onMessage", "onHealthCheck", "capabilities"],
  default_settings: {
    triggers: [`/${id}`],
  },
  config_schema: {
    type: "object",
    properties: {
      triggers: { type: "array", items: { type: "string" } },
    },
    additionalProperties: false,
  },
});

writeText("index.js", [
  "function onMessage(ctx) {",
  "  const text = String(ctx.text || '').trim();",
  "  const triggers = ctx.settings.triggers || [];",
  "  if (!triggers.some((trigger) => text === String(trigger || '').trim())) {",
  "    return { handled: false };",
  "  }",
  "  return { handled: true, reply: '' };",
  "}",
  "",
  "function onHealthCheck() {",
  "  return { ok: true, detail: 'ready' };",
  "}",
  "",
  "function capabilities(ctx) {",
  "  return { commands: ctx.settings.triggers || [] };",
  "}",
  "",
  "module.exports = { onMessage, onHealthCheck, capabilities };",
  "",
].join("\n"));

writeText("README.md", [
  `# ${titleFromID(id)}`,
  "",
  "Plugin scaffold generated by `npm run create:plugin -- <id>`.",
  "",
  "## Hooks",
  "",
  "- `onMessage`",
  "- `onHealthCheck`",
  "- `capabilities`",
  "",
].join("\n"));

writeText(path.join("tests", "plugin.test.js"), [
  "const assert = require('assert');",
  "const plugin = require('../index');",
  "",
  "assert.deepStrictEqual(plugin.onMessage({",
  `  text: '/${id}',`,
  `  settings: { triggers: ['/${id}'] },`,
  "}), { handled: true, reply: '' });",
  "",
  "assert.deepStrictEqual(plugin.onMessage({",
  "  text: 'nope',",
  `  settings: { triggers: ['/${id}'] },`,
  "}), { handled: false });",
  "",
  `console.log('${id} plugin tests ok');`,
  "",
].join("\n"));

console.log(`created plugin ${id}: ${path.relative(root, dir)}`);

function write(relative, value) {
  writeText(relative, `${JSON.stringify(value, null, 2)}\n`);
}

function writeText(relative, text) {
  const target = path.join(dir, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, text, "utf8");
}

function titleFromID(value) {
  return String(value).split(/[-_]/).map((part) => part ? `${part[0].toUpperCase()}${part.slice(1)}` : part).join(" ");
}

function readHostVersion() {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
    return String(pkg.version || "0.0.0");
  } catch {
    return "0.0.0";
  }
}
